# Generated by Django 4.2 on 2023-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('clgname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cgpa', models.IntegerField()),
                ('dob', models.DateField()),
                ('branch', models.DateField()),
            ],
        ),
    ]
